export const freeDrivers = [
  {
    id: 1,
    name: "Juma Mwaura",
    completedrides: 100,
    photo: "/driverpic.svg",
    commissiondue: 650,
    availablefor: "Rides",
    vehicle: "KDS 004B",
    rating: "4.2",
    ratingphoto: "rating.svg",
    pendingpayout: "ksh 2000",
  },
  {
    id: 2,
    name: "John Kamau",
    completedrides: 80,
    photo: "/driverpic.svg",
    commissiondue: 500,
    availablefor: "Deliveries",
    vehicle: "KAB 123C",
    rating: "4.0",
    ratingphoto: "rating.svg",
    pendingpayout: "ksh 1800",
  },
  {
    id: 3,
    name: "Mary Wambui",
    completedrides: 120,
    photo: "/driverpic.svg",
    commissiondue: 700,
    availablefor: "Rides",
    vehicle: "KBC 456D",
    rating: "4.7",
    ratingphoto: "rating.svg",
    pendingpayout: "ksh 2200",
  },
  {
    id: 4,
    name: "Peter Otieno",
    completedrides: 90,
    photo: "/driverpic.svg",
    commissiondue: 550,
    availablefor: "Deliveries",
    vehicle: "KCD 789E",
    rating: "4.1",
    ratingphoto: "rating.svg",
    pendingpayout: "ksh 1600",
  },
];

export const freeColumns = [
  { header: "Name", accessor: "name" },
  { header: "Completed Rides", accessor: "completedrides" },
  { header: "Rating", accessor: "rating" },
  { header: "Commission Due", accessor: "commissiondue" },
  { header: "Pending Payout", accessor: "pendingpayout" },
  { header: "Vehicle", accessor: "vehicle" },
  { header: "Available For", accessor: "availablefor" },
];

export const occupiedDrivers = [
  {
    id: 5,
    name: "Jane Doe",
    completedrides: 50,
    photo: "/driverpic.svg",
    commissiondue: 300,
    currentorder: "Deliveries",
    vehicle: "KCS 123A",
    rating: "4.5",
    ratingphoto: "rating.svg",
    pendingpayout: "ksh 1500",
  },
  {
    id: 6,
    name: "Lucy Akinyi",
    completedrides: 60,
    photo: "/driverpic.svg",
    commissiondue: 400,
    currentorder: "Rides",
    vehicle: "KDE 012F",
    rating: "4.3",
    ratingphoto: "rating.svg",
    pendingpayout: "ksh 1200",
  },
  {
    id: 7,
    name: "James Omondi",
    completedrides: 70,
    photo: "/driverpic.svg",
    commissiondue: 450,
    currentorder: "Deliveries",
    vehicle: "KEF 345G",
    rating: "4.0",
    ratingphoto: "rating.svg",
    pendingpayout: "ksh 1300",

  },
  {
    id: 8,
    name: "Grace Atieno",
    completedrides: 110,
    photo: "/driverpic.svg",
    commissiondue: 600,
    currentorder: "Rides",
    vehicle: "KFG 678H",
    rating: "4.6",
    ratingphoto: "rating.svg",
    pendingpayout: "ksh 1900",
  },
];

export const occupiedColumns = [
  { header: "Name", accessor: "name" },
  { header: "Completed Rides", accessor: "completedrides" },
  { header: "Rating", accessor: "rating" },
  { header: "Commission Due", accessor: "commissiondue" },
  { header: "Pending Payout", accessor: "pendingpayout" },
  { header: "Vehicle", accessor: "vehicle" },
  { header: "Current Order", accessor: "currentorder" },
];
  
  export const offlineDrivers = [
    {
      id: 9,
      name: "John Kamau",
      completedrides: 80,
      photo: "/driverpic.svg",
      commissiondue: 500,
      Status: "Offline",
      vehicle: "KAB 123C",
      rating: "4.0",
      ratingphoto: "rating.svg",
      pendingpayout: "ksh 1800",
      lastseen: "3 hours ago",
    },
    {
      id: 10,
      name: "Mary Wambui",
      completedrides: 120,
      photo: "/driverpic.svg",
      commissiondue: 700,
      Status: "Offline",
      vehicle: "KBC 456D",
      rating: "4.7",
      ratingphoto: "rating.svg",
      pendingpayout: "ksh 2200",
      lastseen: "5 hours ago",
    },
    // Add more data here
  ];

  // Columns for Offline Drivers Table
export const offlineColumns = [
    { header: "Name", accessor: "name" },
    { header: "Completed Rides", accessor: "completedrides" },
    { header: "Rating", accessor: "rating" },
    { header: "Commission Due", accessor: "commissiondue" },
    { header: "Pending Payouts", accessor: "pendingpayout" },
    { header: "Last Seen", accessor: "lastseen" },
    { header: "Vehicle", accessor: "vehicle" },
  ];
  
  export const unapprovedDrivers = [
    {
      id: 11,
      name: "Daniel Kipchumba",
      photo: "/driverpic.svg",
      vehicleclass: "Car",
      propulsion: "Fuel",
      age: 28,
      location: "Nairobi",
      date: "Dec 30,2024 05.18",
    },
    {
      id: 12,
      name: "Sarah Wanjiku",
      photo: "/driverpic.svg",
      vehicleclass: "Car",
      propulsion: "Electrical",
      age: 35,
      location: "Mombasa",
      date: "Jan 10,2025 11.18",
    },
    {
      id: 13,
      name: "Michael Otieno",
      photo: "/driverpic.svg",
      vehicleclass: "Car",
      propulsion: "Fuel",
      age: 30,
      location: "Kisumu",
      date: "Jan 15,2025 09.00",
    },
    {
      id: 14,
      name: "Esther Muthoni",
      photo: "/driverpic.svg",
      vehicleclass: "Motorbike",
      propulsion: "Electrical",
      age: 32,
      location: "Nakuru",
      date: "Jan 20,2025 14.30",
    },
  ];
  
  export const unapprovedColumns = [
    { header: "Name", accessor: "name" },
    { header: "Vehicle Class", accessor: "vehicleclass" },
    { header: "Propulsion", accessor: "propulsion" },
    { header: "Age", accessor: "age" },
    { header: "Location", accessor: "location" },
    { header: "Date", accessor: "date" },
  ];
  
  
  export const inactiveDrivers = [
    {
      id: 15,
      name: "James Omondi",
      completedrides: 60,
      photo: "/driverpic.svg",
      commissiondue: 400,
      Status: "Inactive",
      vehicle: "KCD 789E",
      rating: "4.1",
      ratingphoto: "rating.svg",
      pendingpayout: "ksh 1200",
      lastseen: "Jan 14,2025 05:24",
      reason: "At rest",
    },
    {
      id: 16,
      name: "Grace Atieno",
      completedrides: 90,
      photo: "/driverpic.svg",
      commissiondue: 550,
      Status: "Inactive",
      vehicle: "KDE 012F",
      rating: "4.3",
      ratingphoto: "rating.svg",
      lastseen: "Dec 14,2024 15:24",
      pendingpayout: "ksh 1600",
      reason: "Due to commission",
    },
    {
      id: 17,
      name: "Peter Otieno",
      completedrides: 70,
      photo: "/driverpic.svg",
      commissiondue: 450,
      Status: "Inactive",
      vehicle: "KEF 345G",
      rating: "4.0",
      ratingphoto: "rating.svg",
      pendingpayout: "ksh 1300",
      lastseen: "Jan 15,2025 09:00",
      reason: "At rest",
    },
    {
      id: 18,
      name: "Lucy Akinyi",
      completedrides: 110,
      photo: "/driverpic.svg",
      commissiondue: 600,
      Status: "Inactive",
      vehicle: "KFG 678H",
      rating: "4.6",
      ratingphoto: "rating.svg",
      pendingpayout: "ksh 1900",
      lastseen: "Jan 20,2025 14:30",
      reason: "Due to commission",
    },
  ];
  
  export const inactiveColumns = [
    { header: "Name", accessor: "name" },
    { header: "Completed Rides", accessor: "completedrides" },
    { header: "Rating", accessor: "rating" },
    { header: "Commission Due", accessor: "commissiondue" },
    { header: "Pending Payout", accessor: "pendingpayout" },
    { header: "Last Seen", accessor: "lastseen" },
    { header: "Vehicle", accessor: "vehicle" },
    { header: "Reason", accessor: "reason" },
  ];
  
  export const deletedDrivers = [
    {
      id: 19,
      name: "Daniel Kipchumba",
      completedrides: 70,
      photo: "/driverpic.svg",
      commissiondue: 450,
      Status: "Deleted",
      vehicle: "KEF 345G",
      rating: "4.0",
      ratingphoto: "rating.svg",
      pendingpayout: "ksh 1300",
      date: "2023-08-15",
      reason: "Violation of Terms",
    },
    {
      id: 20,
      name: "Sarah Wanjiku",
      completedrides: 110,
      photo: "/driverpic.svg",
      commissiondue: 600,
      Status: "Deleted",
      vehicle: "KFG 678H",
      rating: "4.6",
      ratingphoto: "rating.svg",
      pendingpayout: "ksh 1900",
      date: "2023-07-20",
      reason: "Account Deletion Request",
    },
    // Add more data here
  ];

  export const deletedColumns = [
    { header: "Name", accessor: "name" },
    { header: "Completed Rides", accessor: "completedrides" },
    { header: "Rating", accessor: "rating" },
    { header: "Commission Due", accessor: "commissiondue" },
    { header: "Pending Payout", accessor: "pendingpayout" },
    { header: "Date", accessor: "date" },
    { header: "Vehicle", accessor: "vehicle" },
    { header: "Reason", accessor: "reason" },
  ];
  
  export const blockedDrivers = [
    {
      id: 21,
      name: "Michael Otieno",
      completedrides: 85,
      photo: "/driverpic.svg",
      commissiondue: 500,
      Status: "Suspended",
      vehicle: "KGH 901I",
      rating: "4.2",
      ratingphoto: "rating.svg",
      pendingpayout: "ksh 1400",
      reason: "Incomplete Details",
    },
    {
      id: 22,
      name: "Esther Muthoni",
      completedrides: 95,
      photo: "/driverpic.svg",
      commissiondue: 580,
      Status: "Declined Application",
      vehicle: "KHI 234J",
      rating: "4.4",
      ratingphoto: "rating.svg",
      pendingpayout: "ksh 1700",
      reason: "Incomplete Details",
    },
    {
      id: 23,
      name: "Daniel Kipchumba",
      completedrides: 70,
      photo: "/driverpic.svg",
      commissiondue: 450,
      Status: "Declined Application",
      vehicle: "KEF 345G",
      rating: "4.0",
      ratingphoto: "rating.svg",
      pendingpayout: "ksh 1300",
      reason: "Rudeness",
    },
    {
      id: 24,
      name: "Sarah Wanjiku",
      completedrides: 110,
      photo: "/driverpic.svg",
      commissiondue: 600,
      Status: "Suspended",
      vehicle: "KFG 678H",
      rating: "4.6",
      ratingphoto: "rating.svg",
      pendingpayout: "ksh 1900",
      reason: "Rudeness",
    },
  ];
  
  export const blockedColumns = [
    { header: "Name", accessor: "name" },
    { header: "Completed Rides", accessor: "completedrides" },
    { header: "Rating", accessor: "rating" },
    { header: "Commission Due", accessor: "commissiondue" },
    { header: "Pending Payout", accessor: "pendingpayout" },
    { header: "Vehicle", accessor: "vehicle" },
    { header: "Status", accessor: "Status" },
    { header: "Reason", accessor: "reason" },
  ];